# Generated by Django 4.1 on 2022-08-20 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rewardpoints',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='rewardpoints',
            name='value',
            field=models.CharField(default='', max_length=500),
        ),
    ]
