# Generated by Django 4.1 on 2022-08-20 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_rewardpoints_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rewardpoints',
            name='value',
            field=models.IntegerField(default='', max_length=500),
        ),
    ]
