# Generated by Django 4.1 on 2022-12-04 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_log_alter_rewardpoints_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='date',
            field=models.DateTimeField(blank=True, default='04.12.2022 13:51:11'),
        ),
    ]
