# Generated by Django 4.1 on 2022-12-04 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_log_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='date',
            field=models.DateField(blank=True, default='13:54:49'),
        ),
    ]
