# Generated by Django 4.1 on 2022-12-04 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_log_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='date',
            field=models.DateField(blank=True, default='04.12.2022 14:41:32'),
        ),
    ]
